#!/usr/bin/env bash
# configures nginx with custom header HTTP response
# shellcheck disable=SC2059
name=$(hostname)
string1="add_header X-Served-By "
string2=";"
line=$string1$name$string2
sed -i "s/\# Uncomment to enable naxsi on this location/$line/g" /etc/nginx/sites-enabled/default
service nginx restart
