#!/usr/bin/env bash
# debug apache server to return a page when querying the root of it
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
service nginx stop
