#!/usr/bin/env bash
# configures a new Ubuntu machine with installed nginx web server
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
sudo service nginx start
