#!/usr/bin/env bash
# configure Nginx server so that /redirect_me is redirecting to another page
new_string="location /redirect_me/index.html {\n
                 rewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n
        }\n\n        # Only for nginx-naxsi used with nginx-naxsi-ui : process denied requests"
sed -i "s/        # Only for nginx-naxsi used with nginx-naxsi-ui : process denied requests/$new_string/" /etc/nginx/sites-available/default
