#!/usr/bin/env bash
# configure Nginx server to have a custom 404 page
apt-get update
apt-get -y install nginx
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page " > /usr/share/nginx/html/404.html
string1="#error_page 404"
string2="error_page 404"
sed -i "s/$string1/$string2/g" /etc/nginx/sites-available/default
service nginx start
