#!/usr/bin/env bash
# configure Nginx server to have a custom 404 page
echo "Ceci n'est pas une page \n" > /usr/share/nginx/html/404.html
string1="#error_page 404"
string2="error_page 404"
sed -i "s/$string1/$string2/g" /etc/nginx/sites-available/default
