#!/usr/bin/env bash
# debug apache server to return a page when querying the root of it
sudo service nginx stop
cd /usr/share/nginx/html
nohup python -m SimpleHTTPServer 80 </dev/null >/dev/null 2>&1 &
