#!/usr/bin/env bash
#runs nginx as nginx user and listens on 8080
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-enabled/default
pkill apache2
sudo -u nginx service nginx restart
